/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOwnerRouteImport } from './routes/api/public/owner'
import { Route as ApiPublicStolensiteSplatRouteImport } from './routes/api/public/stolensite/$'
import { Route as ApiPublicBrotatoSplatRouteImport } from './routes/api/public/brotato/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOwnerRoute = ApiPublicOwnerRouteImport.update({
  id: '/api/public/owner',
  path: '/api/public/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStolensiteSplatRoute =
  ApiPublicStolensiteSplatRouteImport.update({
    id: '/api/public/stolensite/$',
    path: '/api/public/stolensite/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBrotatoSplatRoute = ApiPublicBrotatoSplatRouteImport.update({
  id: '/api/public/brotato/$',
  path: '/api/public/brotato/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/owner': typeof ApiPublicOwnerRoute
  '/api/public/brotato/$': typeof ApiPublicBrotatoSplatRoute
  '/api/public/stolensite/$': typeof ApiPublicStolensiteSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/owner': typeof ApiPublicOwnerRoute
  '/api/public/brotato/$': typeof ApiPublicBrotatoSplatRoute
  '/api/public/stolensite/$': typeof ApiPublicStolensiteSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/owner': typeof ApiPublicOwnerRoute
  '/api/public/brotato/$': typeof ApiPublicBrotatoSplatRoute
  '/api/public/stolensite/$': typeof ApiPublicStolensiteSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/owner'
    | '/api/public/brotato/$'
    | '/api/public/stolensite/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/owner'
    | '/api/public/brotato/$'
    | '/api/public/stolensite/$'
  id:
    | '__root__'
    | '/'
    | '/api/public/owner'
    | '/api/public/brotato/$'
    | '/api/public/stolensite/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicOwnerRoute: typeof ApiPublicOwnerRoute
  ApiPublicBrotatoSplatRoute: typeof ApiPublicBrotatoSplatRoute
  ApiPublicStolensiteSplatRoute: typeof ApiPublicStolensiteSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/owner': {
      id: '/api/public/owner'
      path: '/api/public/owner'
      fullPath: '/api/public/owner'
      preLoaderRoute: typeof ApiPublicOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stolensite/$': {
      id: '/api/public/stolensite/$'
      path: '/api/public/stolensite/$'
      fullPath: '/api/public/stolensite/$'
      preLoaderRoute: typeof ApiPublicStolensiteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brotato/$': {
      id: '/api/public/brotato/$'
      path: '/api/public/brotato/$'
      fullPath: '/api/public/brotato/$'
      preLoaderRoute: typeof ApiPublicBrotatoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicOwnerRoute: ApiPublicOwnerRoute,
  ApiPublicBrotatoSplatRoute: ApiPublicBrotatoSplatRoute,
  ApiPublicStolensiteSplatRoute: ApiPublicStolensiteSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
