/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicProxySplatRouteImport } from './routes/api/public/proxy/$'
import { Route as ApiPublicDeglovedSplatRouteImport } from './routes/api/public/degloved/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxySplatRoute = ApiPublicProxySplatRouteImport.update({
  id: '/api/public/proxy/$',
  path: '/api/public/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeglovedSplatRoute = ApiPublicDeglovedSplatRouteImport.update({
  id: '/api/public/degloved/$',
  path: '/api/public/degloved/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/degloved/$': typeof ApiPublicDeglovedSplatRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/degloved/$': typeof ApiPublicDeglovedSplatRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/degloved/$': typeof ApiPublicDeglovedSplatRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/degloved/$' | '/api/public/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/degloved/$' | '/api/public/proxy/$'
  id: '__root__' | '/' | '/api/public/degloved/$' | '/api/public/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDeglovedSplatRoute: typeof ApiPublicDeglovedSplatRoute
  ApiPublicProxySplatRoute: typeof ApiPublicProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy/$': {
      id: '/api/public/proxy/$'
      path: '/api/public/proxy/$'
      fullPath: '/api/public/proxy/$'
      preLoaderRoute: typeof ApiPublicProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/degloved/$': {
      id: '/api/public/degloved/$'
      path: '/api/public/degloved/$'
      fullPath: '/api/public/degloved/$'
      preLoaderRoute: typeof ApiPublicDeglovedSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDeglovedSplatRoute: ApiPublicDeglovedSplatRoute,
  ApiPublicProxySplatRoute: ApiPublicProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
