/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicStolensiteSplatRouteImport } from './routes/api/public/stolensite/$'
import { Route as ApiPublicNikehubSplatRouteImport } from './routes/api/public/nikehub/$'
import { Route as ApiPublicDeglovedSplatRouteImport } from './routes/api/public/degloved/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStolensiteSplatRoute =
  ApiPublicStolensiteSplatRouteImport.update({
    id: '/api/public/stolensite/$',
    path: '/api/public/stolensite/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNikehubSplatRoute = ApiPublicNikehubSplatRouteImport.update({
  id: '/api/public/nikehub/$',
  path: '/api/public/nikehub/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeglovedSplatRoute = ApiPublicDeglovedSplatRouteImport.update({
  id: '/api/public/degloved/$',
  path: '/api/public/degloved/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/degloved/$': typeof ApiPublicDeglovedSplatRoute
  '/api/public/nikehub/$': typeof ApiPublicNikehubSplatRoute
  '/api/public/stolensite/$': typeof ApiPublicStolensiteSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/degloved/$': typeof ApiPublicDeglovedSplatRoute
  '/api/public/nikehub/$': typeof ApiPublicNikehubSplatRoute
  '/api/public/stolensite/$': typeof ApiPublicStolensiteSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/degloved/$': typeof ApiPublicDeglovedSplatRoute
  '/api/public/nikehub/$': typeof ApiPublicNikehubSplatRoute
  '/api/public/stolensite/$': typeof ApiPublicStolensiteSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/degloved/$'
    | '/api/public/nikehub/$'
    | '/api/public/stolensite/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/degloved/$'
    | '/api/public/nikehub/$'
    | '/api/public/stolensite/$'
  id:
    | '__root__'
    | '/'
    | '/api/public/degloved/$'
    | '/api/public/nikehub/$'
    | '/api/public/stolensite/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDeglovedSplatRoute: typeof ApiPublicDeglovedSplatRoute
  ApiPublicNikehubSplatRoute: typeof ApiPublicNikehubSplatRoute
  ApiPublicStolensiteSplatRoute: typeof ApiPublicStolensiteSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stolensite/$': {
      id: '/api/public/stolensite/$'
      path: '/api/public/stolensite/$'
      fullPath: '/api/public/stolensite/$'
      preLoaderRoute: typeof ApiPublicStolensiteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nikehub/$': {
      id: '/api/public/nikehub/$'
      path: '/api/public/nikehub/$'
      fullPath: '/api/public/nikehub/$'
      preLoaderRoute: typeof ApiPublicNikehubSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/degloved/$': {
      id: '/api/public/degloved/$'
      path: '/api/public/degloved/$'
      fullPath: '/api/public/degloved/$'
      preLoaderRoute: typeof ApiPublicDeglovedSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDeglovedSplatRoute: ApiPublicDeglovedSplatRoute,
  ApiPublicNikehubSplatRoute: ApiPublicNikehubSplatRoute,
  ApiPublicStolensiteSplatRoute: ApiPublicStolensiteSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
